import WalletRepository from '../repositories/WalletRepository';
import KycRepository from '../repositories/KycRepository';
import monnify from '../libraries/monnify';
import appConfig from '../../config/appConfig';
import { Types } from 'mongoose';

class VirtualAccountService {
    async getOrCreateVirtualAccount(userId: string, forceRefresh = false) {
        const userObjId = new Types.ObjectId(userId);
        
        // 1. Check if wallet already has a virtual account
        const wallet = await WalletRepository.getWalletByOwner('user', userObjId);
        if (!wallet) {
            throw new Error('Wallet not found for this user');
        }

        if (wallet.virtualAccount && wallet.virtualAccount.accountNumber && !forceRefresh) {
            return wallet.virtualAccount;
        }

        // 2. Fetch KYC for NIN/BVN
        const kyc = await KycRepository.getKycByUser(userObjId);
        
        const bvn = kyc?.bvn?.bvn;
        const nin = kyc?.identity?.identityType === 'nin' ? kyc?.identity?.identityNumber : undefined;

        if (!kyc || (!bvn && !nin)) {
            throw new Error('Please update your KYC with a valid BVN or NIN to generate a virtual account');
        }

        const user = kyc.user as any; // Populated user

        // 3. Initiate Monnify Reservation
        const accessToken = await monnify.genToken();
        const accountReference = `USER_WAL_${userId}`;
        
        const payload: any = {
            accountReference,
            accountName: `Terminus - ${user.firstName} ${user.lastName}`,
            currencyCode: 'NGN',
            contractCode: appConfig.monnify.contractCode,
            customerEmail: user.email,
            customerName: `${user.firstName} ${user.lastName}`,
            getAllAvailableBanks: true
        };

        if (bvn) payload.bvn = bvn;
        if (nin) payload.nin = nin;

        const response = await monnify.reserveAccount(payload, accessToken);

        if (!response.requestSuccessful) {
            console.error('Monnify Reservation Failed:', response.responseMessage);
            throw new Error(response.responseMessage || 'Failed to generate virtual account');
        }

        // 4. Extract account details (usually returns multiple banks, we take the first or specific one)
        const accounts = response.responseBody.accounts;
        if (!accounts || accounts.length === 0) {
            throw new Error('No virtual accounts generated by provider');
        }

        const primaryAccount = accounts[0]; // Take the first one (e.g. Wema or Moniepoint)

        const virtualAccountData = {
            bankName: primaryAccount.bankName,
            accountNumber: primaryAccount.accountNumber,
            accountName: response.responseBody.accountName,
            accountReference: response.responseBody.accountReference,
            bankCode: primaryAccount.bankCode
        };

        // 5. Update Wallet
        await WalletRepository.updateWallet(wallet._id, {
            virtualAccount: virtualAccountData
        });

        return virtualAccountData;
    }
}

export default new VirtualAccountService();
