import WalletRepository from '../repositories/WalletRepository';
import KycRepository from '../repositories/KycRepository';
import monnify from '../libraries/monnify';
import appConfig from '../../config/appConfig';
import { Types } from 'mongoose';

class VirtualAccountService {
    async getOrCreateVirtualAccount(
        userId: string,
        forceRefresh = false,
        role: 'user' | 'vendor' = 'user'
    ) {
        const userObjId = new Types.ObjectId(userId);

        // 1. Look up the correct wallet for the given role
        const wallet = await WalletRepository.getWalletByOwner(role, userObjId);
        if (!wallet) {
            throw new Error(`Wallet not found for this ${role}`);
        }

        // Return cached virtual account if it exists and refresh is not forced
        if (wallet.virtualAccount && wallet.virtualAccount.accountNumber && !forceRefresh) {
            return wallet.virtualAccount;
        }

        // 2. Fetch KYC for NIN (optional)
        const kyc = await KycRepository.getKycByUser(userObjId);

        const userNin = kyc?.nin?.nin || (kyc?.identity?.identityType === 'nin' ? kyc?.identity?.identityNumber : undefined);
        const nin = appConfig.monnify.directorNin || userNin;

        let user: any = null;
        if (kyc && kyc.user) {
            user = kyc.user;
        } else {
            const UserRepository = (await import('../repositories/UserRepository')).default;
            user = await UserRepository.findUserById(userId);
        }

        if (!user) {
            throw new Error('User details not found to generate virtual account');
        }

        // 3. Initiate Monnify Reservation
        // Scope the reference by role so vendor and customer accounts never collide
        const accessToken = await monnify.genToken();
        const accountReference = role === 'vendor'
            ? `VENDOR_WAL_${userId}`
            : `USER_WAL_${userId}`;

        const payload: any = {
            accountReference,
            accountName: `Terminus - ${user.firstName} ${user.lastName}`,
            currencyCode: 'NGN',
            contractCode: appConfig.monnify.contractCode,
            customerEmail: user.email,
            customerName: `${user.firstName} ${user.lastName}`,
            getAllAvailableBanks: true
        };

        if (nin) {
            payload.nin = nin;
        }

        const response = await monnify.reserveAccount(payload, accessToken);

        // Handle "already reserved" gracefully — fetch the existing reservation
        if (
            !response.requestSuccessful &&
            typeof response.responseMessage === 'string' &&
            response.responseMessage.toLowerCase().includes('already')
        ) {
            console.warn(`[VirtualAccountService] Account reference ${accountReference} already exists, fetching existing reservation.`);
            const existing = await monnify.getReservedAccount(accountReference, accessToken);
            if (existing?.requestSuccessful && existing.responseBody?.accounts?.length) {
                const acc = existing.responseBody.accounts[0];
                const virtualAccountData = {
                    bankName: acc.bankName,
                    accountNumber: acc.accountNumber,
                    accountName: existing.responseBody.accountName,
                    accountReference: existing.responseBody.accountReference,
                    bankCode: acc.bankCode
                };
                await WalletRepository.updateWallet(wallet._id, { virtualAccount: virtualAccountData });
                return virtualAccountData;
            }
        }

        if (!response.requestSuccessful) {
            console.error('Monnify Reservation Failed:', response.responseMessage);
            throw new Error(response.responseMessage || 'Failed to generate virtual account');
        }

        // 4. Extract account details
        const accounts = response.responseBody.accounts;
        if (!accounts || accounts.length === 0) {
            throw new Error('No virtual accounts generated by provider');
        }

        const primaryAccount = accounts[0];

        const virtualAccountData = {
            bankName: primaryAccount.bankName,
            accountNumber: primaryAccount.accountNumber,
            accountName: response.responseBody.accountName,
            accountReference: response.responseBody.accountReference,
            bankCode: primaryAccount.bankCode
        };

        // 5. Update Wallet
        await WalletRepository.updateWallet(wallet._id, {
            virtualAccount: virtualAccountData
        });

        return virtualAccountData;
    }
}

export default new VirtualAccountService();

